apiVersion: v2
name: blockchain-node
description: A Helm chart for Kubernetes

keywords:
  - blockchain
  - web3

maintainers:
  - email: vladzaq1@protonmail.com
    name: vlad

type: application

version: 0.1.0
