statefulset:
  - name: axelar
    replicas: 1
    persistence:
      size: 200Gi
      storageClassName: local-path
      dataMountPath: /data
    initContainers:
      - name: restore-from-snapshot
        image: alpine:latest
        workingDir: /data
        command:
          - /bin/sh
          - -c
          - |
            set -x
            apk add curl tar lz4 wget

            echo "Download the snapshot"
            mkdir -p /data/data
            wget -qO- https://snapshot.nodes.pokt.network/latest.tar.gz | tar -xz -C /data/data

            chown -R 1005:1001 /data
            # sleep 10000000
        volumeMounts:
          - name: pokt-data
            mountPath: /data
        securityContext:
          runAsUser: 0
        # resources:
        #   requests:
        #     cpu: 1
        #     memory: 2Gi
        #   limits:
        #     cpu: 2
        #     memory: 2Gi
    containers:
      - name: pocket-core
        image:
          repository: poktnetwork/pocket-core
          tag: "RC-0.8.3"
        env:
          - name: DATA_TEST
            value: "test_data"
        workingDir: /data
        command: "pocket start \
          --datadir /data \
          --seeds='03b74fa3c68356bb40d58ecc10129479b159a145@seed1.mainnet.pokt.network:20656,64c91701ea98440bc3674fdb9a99311461cdfd6f@seed2.mainnet.pokt.network:21656,0057ee693f3ce332c4ffcb499ede024c586ae37b@seed3.mainnet.pokt.network:22856,9fd99b89947c6af57cd0269ad01ecb99960177cd@seed4.mainnet.pokt.network:23856,f2a4d0ec9d50ea61db18452d191687c899c3ca42@seed5.mainnet.pokt.network:24856,f2a9705924e8d0e11fed60484da2c3d22f7daba8@seed6.mainnet.pokt.network:25856,582177fd65dd03806eeaa2e21c9049e653672c7e@seed7.mainnet.pokt.network:26856,2ea0b13ab823986cfb44292add51ce8677b899ad@seed8.mainnet.pokt.network:27856,a5f4a4cd88db9fd5def1574a0bffef3c6f354a76@seed9.mainnet.pokt.network:28856,d4039bd71d48def9f9f61f670c098b8956e52a08@seed10.mainnet.pokt.network:29856,5c133f07ed296bb9e21e3e42d5f26e0f7d2b2832@poktseed100.chainflow.io:26656,361b1936d3fbe516628ebd6a503920fc4fc0f6a7@seed.pokt.rivet.cloud:26656' \
          --mainnet"
        # resources:
        #   limits:
        #     cpu: 3
        #     memory: 15Gi
        #   requests:
        #     cpu: 2
        #     memory: 10Gi
        ports:
          - name: p2p
            type: LoadBalancer
            port: 30303
            protocol: TCP
          - name: p2p-udp
            type: LoadBalancer
            port: 30303
            protocol: UDP
          - name: rpc
            type: ClusterIP
            port: 8545
            protocol: TCP
            service:
              type: ClusterIP
              annotations:
                cloud.google.com/neg: '{"ingress": true}'
            ingress:
              # enabled: false
              className: "Nginx"
              annotations:
                kubernetes.io/ingress.class: nginx
                kubernetes.io/tls-acme: "true"
              hosts:
                - host: chart-example.local
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
               - secretName: chart-example-tls
                 hosts:
                   - chart-example.local
          - name: prom-metrics
            type: ClusterIP
            port: 6060
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 8545
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8545
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3

global:
  serviceAccount:
    create: true
    name: "pokt"
  securityContext:
    fsGroup: 1001
    runAsUser: 1005
    runAsGroup: 1001
    fsGroupChangePolicy: "OnRootMismatch"
