{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "default" .Values.global.serviceAccount.name }}
  labels:
    {{- include "blockchain-node.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
